### ISSUE TITLE
TypeError: Cannot read property 'direction' of undefined

### ISSUE THREAD

**Issue by mysterywave** [iiegor/slither#101]
[Application][DEBUG] You are running slither-server 0.0.12-dev
[Application][INFO] Starting the server in dev at port 8080...
[Server][INFO] Listening for connections
Snake going to 99

slither-master/src/server.coffee:114
          if (value === conn.snake.direction.angle) {
                                  ^
TypeError: Cannot read property 'direction' of undefined
    at Server.module.exports.Server.handleMessage (slither-master/src/server.coffee:101:38)
    at WebSocket.EventEmitter.emit (events.js:98:17)
    at Receiver.onbinary (slither-master/node_modules/ws/lib/WebSocket.js:823:10)
    at slither-master/node_modules/ws/lib/Receiver.js:537:18
    at slither-master/node_modules/ws/lib/Receiver.js:361:7
    at slither-master/node_modules/ws/lib/PerMessageDeflate.js:238:5
    at afterWrite (_stream_writable.js:274:3)
    at onwrite (_stream_writable.js:266:7)
    at WritableState.onwrite (_stream_writable.js:97:5)
    at afterTransform (_stream_transform.js:99:5)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at Zlib.callback (zlib.js:451:5)

**Comment by ulwanski** [comment]
Same bug here

```
> node ./bin/slither

[Application][DEBUG] You are running slither-server 0.0.12-dev
[Application][INFO] Starting the server in dev at port 8080...
[Server][INFO] Listening for connections
Snake going to 99
/usr/src/slither/src/server.coffee:114
          if (value === conn.snake.direction.angle) {
                                   ^

TypeError: Cannot read property 'direction' of undefined
    at Server.module.exports.Server.handleMessage (/usr/src/slither/src/server.coffee:101:39)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at Receiver.onbinary (/usr/src/slither/node_modules/ws/lib/WebSocket.js:823:10)
    at /usr/src/slither/node_modules/ws/lib/Receiver.js:537:18
    at /usr/src/slither/node_modules/ws/lib/Receiver.js:361:7
    at /usr/src/slither/node_modules/ws/lib/PerMessageDeflate.js:238:5
    at afterWrite (_stream_writable.js:454:3)
    at onwrite (_stream_writable.js:445:7)
    at InflateRaw.afterTransform (_stream_transform.js:90:3)
    at Zlib.callback (zlib.js:515:5)

```

**Comment by kites222** [comment]
mine is

- TypeError: Cannot read properties of undefined (reading 'url')
    at Server.module.exports.Server.handleConnection (C:\Users\BOB\Downloads\slither-0.0.11\slither-0.0.11\src\server.coffee:58:40)
    at WebSocketServer.emit (node:events:518:28)
    at WebSocketServer.completeUpgrade (C:\Users\BOB\Downloads\slither-0.0.11\slither-0.0.11\node_modules\ws\lib\websocket-server.js:438:5)
    at WebSocketServer.handleUpgrade (C:\Users\BOB\Downloads\slither-0.0.11\slither-0.0.11\node_modules\ws\lib\websocket-server.js:346:10)
    at Server.upgrade (C:\Users\BOB\Downloads\slither-0.0.11\slither-0.0.11\node_modules\ws\lib\websocket-server.js:119:16)
    at Server.emit (node:events:518:28)
    at onParserExecuteCommon (node:_http_server:952:14)
    at onParserExecute (node:_http_server:854:3)
