### ISSUE TITLE
No worm after entering server

### ISSUE THREAD

**Issue by gary00k** [iiegor/slither#104]
Hello, I got a problem.
I installed nodejs, installed server (npm install) and after running script and entering 127.0.0.1:8080 I see only background. No snake, no food balls. In cmd I got this:
`
C:\Users\Admin\Desktop\slither-master>npm start

> slither-server@0.0.12-dev start C:\Users\Admin\Desktop\slither-master
> node ./bin/slither

[Application][DEBUG] You are running slither-server 0.0.12-dev
[Application][INFO] Starting the server in dev at port 8080...
[Server][INFO] Listening for connections
Snake going to 99
C:\Users\Admin\Desktop\slither-master\src\server.coffee:114
          if (value === conn.snake.direction.angle) {
                                   ^

TypeError: Cannot read property 'direction' of undefined
    at Server.module.exports.Server.handleMessage (C:\Users\Admin\Desktop\slithe
r-master\src\server.coffee:101:39)
←[90m    at WebSocket.emit (events.js:315:20)←[39m
    at Receiver.onbinary (C:\Users\Admin\Desktop\slither-master\node_modules\←[4
mws←[24m\lib\WebSocket.js:823:10)
    at C:\Users\Admin\Desktop\slither-master\node_modules\←[4mws←[24m\lib\Receiv
er.js:537:18
    at C:\Users\Admin\Desktop\slither-master\node_modules\←[4mws←[24m\lib\Receiv
er.js:361:7
    at C:\Users\Admin\Desktop\slither-master\node_modules\←[4mws←[24m\lib\PerMes
sageDeflate.js:238:5
←[90m    at afterWrite (_stream_writable.js:478:5)←[39m
←[90m    at onwrite (_stream_writable.js:458:7)←[39m
←[90m    at InflateRaw.afterTransform (_stream_transform.js:98:3)←[39m
←[90m    at Zlib.processCallback (zlib.js:578:8)←[39m

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! slither-server@0.0.12-dev start: `node ./bin/slither`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the slither-server@0.0.12-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2021-11-30T09_31_08_
792Z-debug.log

C:\Users\Admin\Desktop\slither-master>`

Can you help me, please?

**Comment by t3knical** [comment]
i fixed that part (was just a matter of sending a preinit packet first) but i seem to have another issue now where once i'm in the game nothing is rendering in the browser window stuff like food and your snake, other stuff such as your name on the leaderboard with a score however is showing up so i'm hoping this is i'm guessing most likely something to do with the new protocol version in the next couple days maybe i can get a some what a working version uploaded using protocol 11 stuff if it is. my goal is so that i can get my 10-15 neat gym bots off their main servers. Also then i could run as many as my computer will let me and not get banned :D

**Comment by t3knical** [comment]
status update: I now have a snake that I can see and move once connected, however the movement of the snake is still not quite exactly like the movement on the official severs, feels laggy, quick on turns and stutterish overall, however with all that being said i'm pretty happy to where i got it so far, from not working at all to actually kind of working.

**Comment by t3knical** [comment]
status update: might just be able to get this updated version out by later today, seems like i have fixed the weird motion stuff and food spawning kind of as well. probably going to try to add in the eat function properly next, 

Edit: sorry got carried away with r/place :)

**Comment by antgame11** [comment]
could you release this version you made?
