### ISSUE TITLE
Build error server

### ISSUE THREAD

**Issue by djoey123** [iiegor/slither#43]
I got this error when i am build the server

```
npm install
\
> utf-8-validate@1.2.1 install /home/pi/Downloads/slither-master/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/pi/Downloads/slither-master/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
In file included from ../src/validation.cc:15:0:
../node_modules/nan/nan.h:328:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
validation.target.mk:84: recipe for target 'Release/obj.target/validation/src/validation.o' failed
make: *** [Release/obj.target/validation/src/validation.o] Error 1
make: Leaving directory '/home/pi/Downloads/slither-master/node_modules/ws/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.8-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Downloads/slither-master/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 

> bufferutil@1.2.1 install /home/pi/Downloads/slither-master/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/pi/Downloads/slither-master/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:0:
../node_modules/nan/nan.h:328:47: error: ‘REPLACE_INVALID_UTF8’ is not a member of ‘v8::String’
   static const unsigned kReplaceInvalidUtf8 = v8::String::REPLACE_INVALID_UTF8;
                                               ^
bufferutil.target.mk:84: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory '/home/pi/Downloads/slither-master/node_modules/ws/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 4.4.8-v7+
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pi/Downloads/slither-master/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm WARN optional dep failed, continuing bufferutil@1.2.1
object-keys@1.0.9 node_modules/object-keys

semver@5.1.0 node_modules/semver

chalk@1.1.3 node_modules/chalk
├── escape-string-regexp@1.0.5
├── supports-color@2.0.0
├── ansi-styles@2.2.1
├── strip-ansi@3.0.1 (ansi-regex@2.0.0)
└── has-ansi@2.0.0 (ansi-regex@2.0.0)

coffee-script@1.10.0 node_modules/coffee-script

ws@0.8.1 node_modules/ws
├── options@0.0.6
└── ultron@1.0.2
```

**Comment by iiegor** [comment]
This error is related with ``ws`` module, maybe this: http://stackoverflow.com/questions/33091923/error-replace-invalid-utf8-is-not-a-member-of-v8string, can help you.
